#!/usr/bin/env python3
"""Weekly Bounty Newsletter Generator — auto-builds from scan data."""
import json, time, os
from datetime import datetime, timezone, timedelta
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"
BOUNTIES_FILE = DATA_DIR / "bounties.json"
MATCHES_FILE = DATA_DIR / "matches.json"
EARNINGS_FILE = DATA_DIR / "earnings.json"
NEWSLETTER_FILE = DATA_DIR / "newsletter.md"
NEWSLETTER_HTML = DATA_DIR / "newsletter.html"

def load_json(path):
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {}

def build():
    bounties = load_json(BOUNTIES_FILE)
    matches = load_json(MATCHES_FILE)
    earnings = load_json(EARNINGS_FILE)

    summary = earnings.get("summary", {})
    now = datetime.now(timezone.utc)
    week = now.strftime("%Y-W%W")

    # Top bounties by value
    with_amount = [b for b in bounties if b.get("amount_usd")]
    with_amount.sort(key=lambda b: b["amount_usd"], reverse=True)
    top_bounties = with_amount[:10]

    # Top matches (S and A tier)
    s_tier = [m for m in matches if m.get("tier") == "S"][:5]
    a_tier = [m for m in matches if m.get("tier") == "A"][:5]

    # New bounties this week
    week_ago = (now - timedelta(days=7)).isoformat()
    new_this_week = [b for b in bounties if b.get("created_at", "") >= week_ago]

    md = f"""# BountyHunter Weekly — {week}

**{now.strftime('%B %d, %Y')}**

---

## 📊 Market Snapshot

| Metric | Value |
|--------|-------|
| Active Bounties | {len(bounties)} |
| Total Value | ${sum(b.get('amount_usd', 0) or 0 for b in bounties):,} |
| New This Week | {len(new_this_week)} |
| S-Tier Matches | {len(s_tier)} |
| A-Tier Matches | {len(a_tier)} |

---

## 🏆 Top 10 Highest-Value Bounties

"""
    for i, b in enumerate(top_bounties, 1):
        amt = b.get("amount_usd") or "?"
        md += f"{i}. **${amt:,}** — [{b['title'][:70]}]({b['url']})\n"
        md += f"   Language: {b.get('language', '?')} | Repo: {b.get('repo', '?')}\n\n"

    md += """---

## 🎯 Best Matches (S-Tier)

"""
    for b in s_tier:
        amt = b.get("amount_usd") or "?"
        md += f"- **${amt:,}** — [{b['title'][:70]}]({b['url']}) ({b.get('language', '?')})\n"

    md += """---

## 📈 Our Progress

"""
    md += f"- Active PRs: {summary.get('open_prs', 0)}\n"
    md += f"- Merged PRs: {summary.get('merged_prs', 0)}\n"
    md += f"- Total Claimed: ${summary.get('total_claimed_usd', 0):,}\n"
    md += f"- Total Earned: ${summary.get('total_earned_usd', 0):,}\n"

    md += """---

## 🛠️ Tools

- [BountyHunter Dashboard](https://luw8072-gif.github.io/bountyhunter/)
- [BountyBoard (All Bounties)](https://luw8072-gif.github.io/bountyboard/)
- [DevToolkit Pro (Free Dev Tools)](https://luw8072-gif.github.io/devtoolkit-pro/)
- [Blog: How to Make Money with GitHub Bounties](https://luw8072-gif.github.io/bountyhunter/blog/how-to-make-money-github-bounties.html)

---

*Auto-generated by BountyHunter. Want this in your inbox? Subscribe at [bountyhunter](https://luw8072-gif.github.io/bountyhunter/).*
"""

    NEWSLETTER_FILE.write_text(md, encoding="utf-8")

    # Also generate simple HTML version
    html = f"""<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>BountyHunter Weekly — {week}</title>
<style>body{{font-family:system-ui;max-width:700px;margin:0 auto;padding:20px;background:#0a0e14;color:#c9d1d9;line-height:1.6}}
h1{{color:#58a6ff}} h2{{color:#d4a72c;margin-top:2rem}} a{{color:#58a6ff}} table{{width:100%;border-collapse:collapse;margin:1rem 0}}
th,td{{padding:8px;text-align:left;border-bottom:1px solid #1e2836}} th{{color:#8b949e;font-size:0.8rem}}
.box{{background:#12171e;border:1px solid #1e2836;border-radius:12px;padding:1.5rem;margin:1rem 0}}
</style></head><body>
<h1>BountyHunter Weekly — {week}</h1>
<p style="color:#8b949e">{now.strftime('%B %d, %Y')}</p>

<div class="box"><h2>Market Snapshot</h2>
<table><tr><th>Metric</th><th>Value</th></tr>
<tr><td>Active Bounties</td><td>{len(bounties)}</td></tr>
<tr><td>Total Value</td><td>${sum(b.get('amount_usd',0) or 0 for b in bounties):,}</td></tr>
<tr><td>New This Week</td><td>{len(new_this_week)}</td></tr>
</table></div>

<div class="box"><h2>Top 10 Bounties</h2>
<ol>{"".join(f'<li><strong>${b.get("amount_usd") or "?"}</strong> <a href="{b["url"]}">{b["title"][:70]}</a></li>' for b in top_bounties)}</ol></div>

<div class="box"><h2>Best Matches (S-Tier)</h2>
<ul>{"".join(f'<li><strong>${b.get("amount_usd") or "?"}</strong> <a href="{b["url"]}">{b["title"][:70]}</a></li>' for b in s_tier)}</ul></div>

<p style="color:#484f58;text-align:center;margin-top:2rem;font-size:0.8rem">Auto-generated by BountyHunter · <a href="https://luw8072-gif.github.io/bountyhunter/">Subscribe</a></p>
</body></html>"""
    NEWSLETTER_HTML.write_text(html, encoding="utf-8")

    print(f"Newsletter generated: {NEWSLETTER_FILE}")
    print(f"HTML version: {NEWSLETTER_HTML}")
    print(f"Top bounties: {len(top_bounties)}, S-tier: {len(s_tier)}, A-tier: {len(a_tier)}")
    print(f"New this week: {len(new_this_week)}")

if __name__ == "__main__":
    build()
